github: [metadata]
permalink: /posts/:title
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate

name: Patrick Miller
url: https://patgmiller.github.io
description: console.log($patrick_brain);
twitter: patgmiller
