permalink: /posts/:title
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate

name: Patrick Miller
url: https://patgmiller.github.io
gravatar_url: https://avatars0.githubusercontent.com/u/3914379
description: posts, and tweets, blogs oh my!
twitter: patgmiller
