permalink: /posts/:title
markdown: kramdown
  input: GFM
gems:
  - jekyll-sitemap

name: Patrick Miller
url: https://patgmiller.github.io
description: >console.log($patrick_brain);
twitter: patgmiller
